services:
  pgsql:
    image: 'postgres:alpine'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PGPASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-database}'
      POSTGRES_USER: '${DB_USER:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/18/docker'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-database}', '-U', '${DB_USER:-user}']
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
