services:
  pgsql:
    image: 'postgres:alpine'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PGPASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-database}'
      POSTGRES_USER: '${DB_USER:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/18/docker'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-database}', '-U', '${DB_USER:-user}']
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8025/livez']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
