/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  PasswordResets: () => import('#controllers/password_resets_controller'),
  Session: () => import('#controllers/session_controller'),
}
