/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DateTime } from 'luxon';

export class ModelPermissionSchema extends BaseModel {
	static $columns = ['createdAt', 'id', 'modelId', 'modelType', 'permissionId', 'updatedAt'] as const;
	$columns = ModelPermissionSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column({ isPrimary: true })
	declare id: bigint | number;
	@column()
	declare modelId: bigint | number | null;
	@column()
	declare modelType: string | null;
	@column()
	declare permissionId: bigint | number | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class ModelRoleSchema extends BaseModel {
	static $columns = ['createdAt', 'id', 'modelId', 'modelType', 'roleId', 'updatedAt'] as const;
	$columns = ModelRoleSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column({ isPrimary: true })
	declare id: bigint | number;
	@column()
	declare modelId: bigint | number | null;
	@column()
	declare modelType: string | null;
	@column()
	declare roleId: bigint | number | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class PermissionSchema extends BaseModel {
	static $columns = [
		'allowed',
		'createdAt',
		'entityId',
		'entityType',
		'id',
		'scope',
		'slug',
		'title',
		'updatedAt',
	] as const;
	$columns = PermissionSchema.$columns;
	@column()
	declare allowed: boolean | null;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column()
	declare entityId: bigint | number | null;
	@column()
	declare entityType: string | null;
	@column({ isPrimary: true })
	declare id: bigint | number;
	@column()
	declare scope: string | null;
	@column()
	declare slug: string | null;
	@column()
	declare title: string | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class ProjectSchema extends BaseModel {
	static $columns = ['createdAt', 'defaultLanguage', 'id', 'name', 'picture', 'slug', 'updatedAt'] as const;
	$columns = ProjectSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare defaultLanguage: string;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare name: string;
	@column()
	declare picture: string | null;
	@column()
	declare slug: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class RoleSchema extends BaseModel {
	static $columns = [
		'allowed',
		'createdAt',
		'entityId',
		'entityType',
		'id',
		'scope',
		'slug',
		'title',
		'updatedAt',
	] as const;
	$columns = RoleSchema.$columns;
	@column()
	declare allowed: boolean | null;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime | null;
	@column()
	declare entityId: bigint | number | null;
	@column()
	declare entityType: string | null;
	@column({ isPrimary: true })
	declare id: bigint | number;
	@column()
	declare scope: string | null;
	@column()
	declare slug: string | null;
	@column()
	declare title: string | null;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}

export class TokenSchema extends BaseModel {
	static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'type', 'userId'] as const;
	$columns = TokenSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column.dateTime()
	declare expiresAt: DateTime;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare token: string;
	@column()
	declare type: string;
	@column()
	declare userId: number;
}

export class UserSchema extends BaseModel {
	static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'updatedAt'] as const;
	$columns = UserSchema.$columns;
	@column.dateTime({ autoCreate: true })
	declare createdAt: DateTime;
	@column()
	declare email: string;
	@column({ isPrimary: true })
	declare id: number;
	@column()
	declare name: string | null;
	@column({ serializeAs: null })
	declare password: string;
	@column.dateTime({ autoCreate: true, autoUpdate: true })
	declare updatedAt: DateTime | null;
}
